tunnel: 2ccf5e13-34fb-44e8-9853-744ac846b560
credentials-file: /Users/dex/.cloudflared/2ccf5e13-34fb-44e8-9853-744ac846b560.json

ingress:
  - hostname: sensores.celtavia.cl
    service: http://localhost:5050
    originRequest:
      noTLSVerify: true
  - service: http_status:404
