tunnel: 7b592bb1-33a6-407f-b150-f370306adef0
credentials-file: /Users/dex/.cloudflared/7b592bb1-33a6-407f-b150-f370306adef0.json

ingress:
  - hostname: sensores.dexfloor.com
    service: http://localhost:5050
    originRequest:
      noTLSVerify: true
  - hostname: sensores.celtavia.cl
    service: http://localhost:5050
    originRequest:
      noTLSVerify: true
  - service: http_status:404
